version: "3.1"

services:
  mongo:
    image: mongo
    ports:
      - 27018:27017
    networks:
      - local
  api:
    image: qaa_api
    ports:
      - 3001:3000
    environment:
      DB_URL: mongodb://mongo:27017
    networks:
      - local
    links:
      - mongo
networks:
  local: